const urlI = "https://st2.depositphotos.com/2001755/8564/i/450/depositphotos_85647140-stock-photo-beautiful-landscape-with-birds.jpg";

const productos = [
    {
        _id: "650a1f1b3e0d3a001c1a4b11",
        image: urlI,
        title: "Automatización Inteligente",
        description: "Controla tus dispositivos de manera eficiente y segura.",
        price: 199.99,
        category: "Domótica",
        brand: "SmartHome",
        rating: 4.8,
        reviews: 320,
        discount: 10,
        features: ["Control remoto", "Compatible con Alexa y Google Home", "Automatización personalizada"],
        warranty: "2 años"
    },
    {
        _id: "650a1f1b3e0d3a001c1a4b12",
        image: urlI,
        title: "Monitoreo Remoto",
        description: "Supervisa tu hogar o negocio desde cualquier parte del mundo.",
        price: 249.99,
        category: "Seguridad",
        brand: "SecureVision",
        rating: 4.6,
        reviews: 250,
        discount: 15,
        features: ["Streaming en vivo", "Detección de movimiento", "Notificaciones en tiempo real"],
        warranty: "3 años"
    },
    {
        _id: "650a1f1b3e0d3a001c1a4b13",
        image: urlI,
        title: "Eficiencia Energética",
        description: "Optimiza el consumo de energía con tecnología IoT.",
        price: 179.99,
        category: "Energía",
        brand: "EcoTech",
        rating: 4.7,
        reviews: 180,
        discount: 5,
        features: ["Monitor de consumo", "Ahorro inteligente", "Integración con paneles solares"],
        warranty: "1 año"
    },
    {
        _id: "650a1f1b3e0d3a001c1a4b14",
        image: urlI,
        title: "Sensor de Movimiento Inteligente",
        description: "Detecta movimientos con precisión y seguridad.",
        price: 89.99,
        category: "Seguridad",
        brand: "MotionGuard",
        rating: 4.5,
        reviews: 210,
        discount: 0,
        features: ["Ángulo de detección 120°", "Notificaciones instantáneas", "Modo nocturno"],
        warranty: "2 años"
    },
    {
        _id: "650a1f1b3e0d3a001c1a4b15",
        image: urlI,
        title: "Control de Iluminación",
        description: "Programa y controla luces de manera remota.",
        price: 129.99,
        category: "Domótica",
        brand: "LightControl",
        rating: 4.9,
        reviews: 500,
        discount: 20,
        features: ["Compatibilidad con asistentes de voz", "Programación horaria", "Modos de ambiente"],
        warranty: "3 años"
    },
    {
        _id: "650a1f1b3e0d3a001c1a4b16",
        image: urlI,
        title: "Asistente de Voz",
        description: "Integra comandos de voz para un hogar inteligente.",
        price: 299.99,
        category: "Domótica",
        brand: "Echo AI",
        rating: 4.7,
        reviews: 280,
        discount: 10,
        features: ["Reconocimiento de voz avanzado", "Conexión con dispositivos IoT", "Reproducción de música"],
        warranty: "1 año"
    },
    {
        _id: "650a1f1b3e0d3a001c1a4b17",
        image: urlI,
        title: "Cámara de Seguridad 360°",
        description: "Vigilancia completa con visión nocturna.",
        price: 349.99,
        category: "Seguridad",
        brand: "SafeGuard",
        rating: 4.8,
        reviews: 400,
        discount: 5,
        features: ["Rotación 360°", "Visión nocturna", "Almacenamiento en la nube"],
        warranty: "2 años"
    },
    {
        _id: "650a1f1b3e0d3a001c1a4b18",
        image: urlI,
        title: "Cerradura Digital",
        description: "Acceso seguro con huella digital y código.",
        price: 199.99,
        category: "Seguridad",
        brand: "LockPro",
        rating: 4.6,
        reviews: 350,
        discount: 12,
        features: ["Huella digital", "Código PIN", "Control remoto vía app"],
        warranty: "3 años"
    },
    {
        _id: "650a1f1b3e0d3a001c1a4b19",
        image: urlI,
        title: "Regulador de Consumo Energético",
        description: "Administra el uso de electricidad con IA.",
        price: 159.99,
        category: "Energía",
        brand: "PowerSaver",
        rating: 4.7,
        reviews: 280,
        discount: 8,
        features: ["Monitor en tiempo real", "Ajuste automático", "Protección contra sobrecargas"],
        warranty: "2 años"
    },
    {
        _id: "650a1f1b3e0d3a001c1a4b20",
        image: urlI,
        title: "Termostato Inteligente",
        description: "Regula la temperatura de forma automática.",
        price: 279.99,
        category: "Climatización",
        brand: "SmartTemp",
        rating: 4.8,
        reviews: 420,
        discount: 15,
        features: ["Control remoto", "Ajuste automático", "Historial de uso"],
        warranty: "2 años"
    },
];

export default productos;
